### ISSUE TITLE
Impute UTC in csv2audata When TZ Not Specified

### ISSUE THREAD

**Issue by guswelter** [autonlab/audata#9]
Assume the following conditions:
- We are using csv2audata to create an audata file from a csv file
- The csv file has a 'time' column which has string representations of times, e.g. "Saturday, September 6, 2020 19:01:01"

Under these conditions, a timezone exception gets raised currently: `TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize`

Please change it so that audata imputes UTC timezone if a timezone is not provided in a string-formatted time column such as this case.

**Comment by vedant-sanil** [comment]
Pandas natively stores date-times as naive timestamps should no timezone or an incorrect timezone be provided. This has been fixed to be localized to the UTC timezone should none be provided. It also defaults to UTC if an incorrect timezone is provided.
